networks:
  tarmo-network:
    driver: bridge

services:
  tarmo-client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: tarmo-client
    ports:
      - "3000:3000"
    depends_on:
      - tarmo
    networks:
      - tarmo-network

  tarmo:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: tarmo
    expose:
      - "9136"
    volumes:
      - ./app/data:/app/data
    networks:
      - tarmo-network